# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-10-05 15:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('person', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='subject_images',
            fields=[
                ('subject_images_id', models.AutoField(primary_key=True, serialize=False)),
                ('picture', models.ImageField(default='pic_folder/None/no-img.jpg', upload_to='pic_folder/')),
                ('file_name', models.CharField(max_length=100, verbose_name='File name')),
                ('mime', models.CharField(max_length=100, verbose_name='Mime')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_images', to='person.Person', verbose_name='Person')),
            ],
            options={
                'verbose_name': 'subject_image',
                'verbose_name_plural': 'subject_images',
            },
        ),
    ]
