# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-10-05 15:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('notes_headers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('note_id', models.AutoField(primary_key=True, serialize=False)),
                ('note_time', models.DateTimeField(help_text='')),
                ('note_text', models.CharField(max_length=100, verbose_name='Note text')),
                ('time_sort_field', models.CharField(max_length=100, verbose_name='Time sort field')),
                ('military', models.IntegerField(verbose_name='Military')),
                ('record_owner', models.CharField(max_length=100, verbose_name='Record owner')),
                ('record_creation_date', models.DateField(help_text='')),
                ('notes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='notes_headers.Notes_header', verbose_name='Notes header')),
            ],
            options={
                'verbose_name': 'note',
                'verbose_name_plural': 'notes',
            },
        ),
    ]
