# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-10-05 15:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import localflavor.us.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('person', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Phone_number',
            fields=[
                ('phone_number_id', models.AutoField(primary_key=True, serialize=False)),
                ('phone_type', models.CharField(choices=[('HOME', 'Home'), ('WORK', 'Work'), ('FAX', 'Fax'), ('MOBILE', 'Mobile'), ('OTHER', 'Other')], max_length=100, verbose_name='Phone type')),
                ('number', localflavor.us.models.PhoneNumberField(help_text='', max_length=20)),
                ('phone_label', models.CharField(max_length=100, verbose_name='Phone label')),
                ('record_owner', models.CharField(max_length=100, verbose_name='Record owner')),
                ('record_creation_date', models.DateField(help_text='')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phone_numbers', to='person.Person', verbose_name='Person')),
            ],
            options={
                'verbose_name': 'phone_number',
                'verbose_name_plural': 'phone_numbers',
            },
        ),
    ]
