# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-10-05 15:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('investigative_cases', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Case_expense',
            fields=[
                ('case_expense_id', models.AutoField(primary_key=True, serialize=False)),
                ('expense_date', models.DateField(help_text='')),
                ('description', models.CharField(max_length=100, verbose_name='Description')),
                ('amount', models.FloatField(verbose_name='Amount')),
                ('total', models.FloatField(verbose_name='Total')),
                ('investigative_case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='investigative_cases.Investigative_case', verbose_name='Investigative case')),
                ('investigator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='users.User', verbose_name='User')),
            ],
            options={
                'verbose_name': 'case_expense',
                'verbose_name_plural': 'case_expenses',
            },
        ),
    ]
