# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-10-06 20:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case_expenses', '0004_auto_20171006_1835'),
    ]

    operations = [
        migrations.RenameField(
            model_name='case_expense',
            old_name='case_expense_id',
            new_name='id',
        ),
        migrations.AlterField(
            model_name='case_expense',
            name='expense_date',
            field=models.DateField(help_text=''),
        ),
    ]
