# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-10-05 15:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('case_contacts', '0001_initial'),
        ('update_types', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='update_option',
            fields=[
                ('update_option_id', models.AutoField(primary_key=True, serialize=False)),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='update_options', to='case_contacts.Case_contact', verbose_name='Case contact')),
                ('update_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='updates', to='update_types.Update_type', verbose_name='Upadate type')),
            ],
            options={
                'verbose_name': 'update_option',
                'verbose_name_plural': 'update_options',
            },
        ),
    ]
