# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-10-05 15:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('investigative_cases', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='objective',
            fields=[
                ('objective_id', models.AutoField(primary_key=True, serialize=False)),
                ('number', models.IntegerField(verbose_name='Number')),
                ('text', models.CharField(max_length=100, verbose_name='Text')),
                ('investigative_case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='objectives', to='investigative_cases.Investigative_case', verbose_name='Investigative case')),
            ],
            options={
                'verbose_name': 'objective',
                'verbose_name_plural': 'objectives',
            },
        ),
    ]
