# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-10-06 20:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mike_ds',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=100, verbose_name='First name')),
            ],
            options={
                'verbose_name': 'mike_ds',
                'verbose_name_plural': 'mike_ds',
            },
        ),
    ]
