# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-10-05 15:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Case_sequence',
            fields=[
                ('case_sequence_id', models.AutoField(primary_key=True, serialize=False)),
                ('case_year', models.IntegerField(verbose_name='Case year')),
                ('case_sequence_number', models.IntegerField(verbose_name='Sequence number')),
                ('case_number', models.CharField(max_length=100, verbose_name='Number')),
            ],
            options={
                'verbose_name': 'case_sequence',
                'verbose_name_plural': 'case_sequences',
            },
        ),
    ]
