# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-10-05 16:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('omc_tickets', '0002_auto_20171005_1551'),
    ]

    operations = [
        migrations.AlterField(
            model_name='omc_ticket',
            name='date_closed',
            field=models.DateTimeField(auto_now_add=True, help_text=''),
        ),
        migrations.AlterField(
            model_name='omc_ticket',
            name='date_opened',
            field=models.DateTimeField(help_text=''),
        ),
    ]
