# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-10-06 20:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('omc_tickets', '0004_auto_20171006_1835'),
    ]

    operations = [
        migrations.RenameField(
            model_name='omc_ticket',
            old_name='omc_ticket_id',
            new_name='id',
        ),
        migrations.AlterField(
            model_name='omc_ticket',
            name='date_closed',
            field=models.DateTimeField(auto_now_add=True, help_text=''),
        ),
        migrations.AlterField(
            model_name='omc_ticket',
            name='date_opened',
            field=models.DateTimeField(help_text=''),
        ),
    ]
