# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-10-06 20:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auto_texts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Auto_text_field',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('field_name', models.CharField(max_length=100, verbose_name='Text')),
                ('parent_auto_text_field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='auto_texts.Auto_text', verbose_name='Auto_text')),
            ],
            options={
                'verbose_name': 'auto_text_field',
                'verbose_name_plural': 'auto_text_fields',
            },
        ),
    ]
