# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-10-05 15:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Word_zip_file',
            fields=[
                ('word_zip_file_id', models.AutoField(primary_key=True, serialize=False)),
                ('file_content', models.FileField(upload_to=None)),
                ('file_name', models.CharField(max_length=100, verbose_name='File name')),
                ('mime', models.CharField(max_length=100, verbose_name='Mime')),
            ],
            options={
                'verbose_name': 'word_zip_file',
                'verbose_name_plural': 'word_zip_files',
            },
        ),
    ]
