# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-10-06 20:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('word_zip_files', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='word_zip_file',
            old_name='word_zip_file_id',
            new_name='id',
        ),
    ]
