# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-10-05 15:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Case_status',
            fields=[
                ('case_status_id', models.AutoField(primary_key=True, serialize=False)),
                ('case_status', models.CharField(choices=[('NEW', 'New'), ('OPEN', 'Open'), ('PENDING_REPORT', 'Pending Report'), ('REPORT_COMPLETE', 'Report Complete'), ('CLOSED', 'Closed'), ('PENDING', 'Pending'), ('INVOICED', 'Invoiced'), ('RUSH_JOB', 'Rush Job')], max_length=100, verbose_name='Case status')),
            ],
            options={
                'verbose_name': 'case_status',
                'verbose_name_plural': 'case_status',
            },
        ),
    ]
