# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-10-05 15:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('person', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='stripe_cc',
            fields=[
                ('stripe_cc_id', models.AutoField(primary_key=True, serialize=False)),
                ('stripe_customer_id', models.CharField(max_length=100, verbose_name='Stripe customer ID')),
                ('cc_last_four', models.CharField(max_length=100, verbose_name='CC last four')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credit_cards', to='person.Person', verbose_name='Person')),
            ],
            options={
                'verbose_name': 'stripe_cc',
                'verbose_name_plural': 'stripe_ccs',
            },
        ),
    ]
