# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-10-06 18:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Auto_text',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=100, verbose_name='Label')),
                ('atext', models.CharField(max_length=100, verbose_name='Text')),
            ],
            options={
                'verbose_name': 'auto_text',
                'verbose_name_plural': 'auto_texts',
            },
        ),
    ]
