# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-10-05 15:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('invoices', '0001_initial'),
        ('expense_types', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice_items',
            fields=[
                ('invoice_items_id', models.AutoField(primary_key=True, serialize=False)),
                ('service_date', models.DateField(help_text='')),
                ('service_end_date', models.DateField(auto_now_add=True, help_text='')),
                ('quantity', models.FloatField(verbose_name='Quantity')),
                ('line_description', models.CharField(max_length=100, verbose_name='Line description')),
                ('rate', models.FloatField(verbose_name='Rate')),
                ('amount', models.FloatField(verbose_name='Amount')),
                ('item_number', models.IntegerField(verbose_name='Item number')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoice_items', to='invoices.Invoice', verbose_name='Invoice')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='line_items', to='expense_types.Expense_type', verbose_name='Expense type')),
            ],
            options={
                'verbose_name': 'invoice_item',
                'verbose_name_plural': 'invoice_items',
            },
        ),
    ]
