# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-10-05 15:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('expense_types', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contractor_rate',
            fields=[
                ('contractor_rate_id', models.AutoField(primary_key=True, serialize=False)),
                ('investigator_id', models.IntegerField(verbose_name='Investigator ID')),
                ('rate', models.FloatField(verbose_name='Rate')),
                ('expense_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contractor_rates', to='expense_types.Expense_type', verbose_name='Expense_type')),
            ],
            options={
                'verbose_name': 'contractor_rate',
                'verbose_name_plural': 'contractor_rates',
            },
        ),
    ]
