# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-10-05 15:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('investigative_cases', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notes_header',
            fields=[
                ('notes_header_id', models.AutoField(primary_key=True, serialize=False)),
                ('investigator_id', models.IntegerField(verbose_name='Investigator ID')),
                ('investigator_name', models.CharField(max_length=100, verbose_name='Investigator name')),
                ('date_worked', models.DateField(help_text='')),
                ('weather', models.CharField(max_length=100, verbose_name='Weather')),
                ('notes_summary', models.CharField(max_length=100, verbose_name='Notes summary')),
                ('city', models.CharField(max_length=100, verbose_name='City')),
                ('state', models.CharField(max_length=100, verbose_name='State')),
                ('notes_complete', models.BooleanField(help_text='')),
                ('wunderground_temp', models.FloatField(help_text='')),
                ('investigative_case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes_headers', to='investigative_cases.Investigative_case', verbose_name='Investigative_case')),
            ],
            options={
                'verbose_name': 'notes_header',
                'verbose_name_plural': 'notes_headers',
            },
        ),
    ]
