# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-10-05 15:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Time_clock',
            fields=[
                ('time_clock_id', models.AutoField(primary_key=True, serialize=False)),
                ('payperiod', models.CharField(max_length=100, verbose_name='Pay period')),
                ('workdate', models.DateField(help_text='')),
                ('timein', models.DateTimeField(help_text='')),
                ('timeout', models.DateTimeField(help_text='')),
                ('original_timein', models.CharField(max_length=100, verbose_name='Original timein')),
                ('original_timeout', models.CharField(max_length=100, verbose_name='Original timeout')),
                ('hoursworked', models.FloatField()),
            ],
            options={
                'verbose_name': 'time_clock',
                'verbose_name_plural': 'time_clock',
            },
        ),
    ]
