# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-10-05 15:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('time_clock', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='time_clock',
            name='timein',
            field=models.DateTimeField(help_text=''),
        ),
        migrations.AlterField(
            model_name='time_clock',
            name='timeout',
            field=models.DateTimeField(help_text=''),
        ),
        migrations.AlterField(
            model_name='time_clock',
            name='workdate',
            field=models.DateField(help_text=''),
        ),
    ]
