# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-10-05 15:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('person', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Investigative_case',
            fields=[
                ('investigative_case_id', models.AutoField(primary_key=True, serialize=False)),
                ('case_number', models.CharField(max_length=100, verbose_name='Case number')),
                ('claim_number', models.CharField(max_length=100, verbose_name='Claim number')),
                ('injury_date', models.DateField(help_text='')),
                ('injury', models.CharField(max_length=100, verbose_name='Injury')),
                ('file_received_date', models.DateField(help_text='')),
                ('case_type', models.CharField(max_length=100, verbose_name='Case type')),
                ('case_status', models.CharField(max_length=100, verbose_name='Case status')),
                ('case_description', models.TextField(max_length=500, verbose_name='Case description')),
                ('case_dollar_budget', models.CharField(max_length=100, verbose_name='Case dollar budget')),
                ('case_time_budget', models.CharField(max_length=100, verbose_name='Case time budget')),
                ('record_owner', models.CharField(max_length=100, verbose_name='Record owner')),
                ('record_creation_date', models.DateField(auto_now_add=True, help_text='')),
                ('primary_investigator', models.IntegerField(verbose_name='Primary investigator')),
                ('is_active', models.BooleanField(help_text='')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cases_client', to='person.Person', verbose_name='Person')),
                ('primary_subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cases_primary_subject', to='person.Person', verbose_name='Person')),
            ],
            options={
                'verbose_name': 'investigative_case',
                'verbose_name_plural': 'investigative_cases',
            },
        ),
    ]
