# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-10-05 15:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('person_id', models.AutoField(primary_key=True, serialize=False)),
                ('prefix', models.CharField(max_length=100, verbose_name='Prefix')),
                ('first_name', models.CharField(max_length=100, verbose_name='First name')),
                ('last_name', models.CharField(max_length=100, verbose_name='Last name')),
                ('middle_name', models.CharField(max_length=100, verbose_name='Middle name')),
                ('suffix', models.CharField(max_length=100, verbose_name='Suffix')),
                ('social_security_number', models.CharField(max_length=100, verbose_name='Middle name')),
                ('date_of_birth', models.DateField(help_text='')),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=100, verbose_name='Gender')),
                ('race', models.CharField(max_length=100, verbose_name='Race')),
                ('height', models.FloatField(help_text='')),
                ('weight', models.FloatField(help_text='')),
                ('hair', models.CharField(max_length=100, verbose_name='Hair')),
                ('build', models.CharField(max_length=100, verbose_name='Build')),
                ('eyes', models.CharField(max_length=100, verbose_name='Eyes')),
                ('glasses', models.CharField(max_length=100, verbose_name='Glasses')),
                ('record_owner', models.CharField(max_length=100, verbose_name='Record owner')),
                ('record_creation_date', models.DateField(auto_now_add=True, help_text='')),
                ('person_type', models.CharField(choices=[('CLIENT', 'Client'), ('SUBJECT', 'Subject'), ('ASSOCIATE', 'Associate'), ('RELATIVE', 'Relative'), ('OTHER', 'Other')], max_length=100, verbose_name='Person type')),
                ('investigative_case', models.CharField(max_length=100, verbose_name='Investigative case')),
                ('is_active', models.BooleanField(help_text='')),
                ('relationship', models.CharField(max_length=100, verbose_name='Relationship')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_contacts', to='companies.Company', verbose_name='Company')),
            ],
            options={
                'verbose_name': 'person',
                'verbose_name_plural': 'person',
            },
        ),
    ]
