# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-10-05 15:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='date_of_birth',
            field=models.DateField(help_text=''),
        ),
        migrations.AlterField(
            model_name='person',
            name='height',
            field=models.FloatField(help_text=''),
        ),
        migrations.AlterField(
            model_name='person',
            name='is_active',
            field=models.BooleanField(help_text=''),
        ),
        migrations.AlterField(
            model_name='person',
            name='record_creation_date',
            field=models.DateField(auto_now_add=True, help_text=''),
        ),
        migrations.AlterField(
            model_name='person',
            name='weight',
            field=models.FloatField(help_text=''),
        ),
    ]
