# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-10-06 20:17
from __future__ import unicode_literals

from django.db import migrations, models
import localflavor.us.models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0004_auto_20171006_1835'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='person_id',
            new_name='id',
        ),
        migrations.AlterField(
            model_name='person',
            name='date_of_birth',
            field=models.DateField(help_text=''),
        ),
        migrations.AlterField(
            model_name='person',
            name='height',
            field=models.FloatField(help_text=''),
        ),
        migrations.AlterField(
            model_name='person',
            name='is_active',
            field=models.BooleanField(help_text=''),
        ),
        migrations.AlterField(
            model_name='person',
            name='record_creation_date',
            field=models.DateField(auto_now_add=True, help_text=''),
        ),
        migrations.AlterField(
            model_name='person',
            name='social_security_number',
            field=localflavor.us.models.USSocialSecurityNumberField(help_text='', max_length=11),
        ),
        migrations.AlterField(
            model_name='person',
            name='weight',
            field=models.FloatField(help_text=''),
        ),
    ]
