# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-10-05 15:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('updates', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Update_media',
            fields=[
                ('update_media_id', models.AutoField(primary_key=True, serialize=False)),
                ('media', models.ImageField(default='pic_folder/None/no-img.jpg', upload_to='pic_folder/')),
                ('file_name', models.CharField(max_length=100, verbose_name='File name')),
                ('mime', models.CharField(max_length=100, verbose_name='Mime')),
                ('blob_size', models.IntegerField(verbose_name='Blob size')),
                ('case_update', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='update_files', to='updates.Update', verbose_name='Update')),
            ],
            options={
                'verbose_name': 'update media',
                'verbose_name_plural': 'update medias',
            },
        ),
    ]
