# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-10-05 15:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('person', '0001_initial'),
        ('investigative_cases', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('invoice_id', models.AutoField(primary_key=True, serialize=False)),
                ('invoce_date', models.DateField(help_text='')),
                ('terms', models.CharField(max_length=100, verbose_name='Terms')),
                ('term_days', models.IntegerField(verbose_name='Term days')),
                ('due', models.CharField(max_length=100, verbose_name='Due')),
                ('invoice_number', models.IntegerField(verbose_name='Invoice number')),
                ('total', models.FloatField(verbose_name='Total')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='person.Person', verbose_name='Person')),
                ('investigative_case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='investigative_cases.Investigative_case', verbose_name='Investigative case')),
            ],
            options={
                'verbose_name': 'invoice',
                'verbose_name_plural': 'invoices',
            },
        ),
    ]
