# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-10-05 15:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import localflavor.us.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('person', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('vehicle_id', models.AutoField(primary_key=True, serialize=False)),
                ('year', models.CharField(max_length=100, verbose_name='Vehicle')),
                ('make', models.CharField(max_length=100, verbose_name='Make')),
                ('model', models.CharField(max_length=100, verbose_name='Model')),
                ('color', models.CharField(max_length=100, verbose_name='Color')),
                ('vin', models.CharField(max_length=100, verbose_name='Vin')),
                ('plate', models.CharField(max_length=100, verbose_name='Plate')),
                ('plate_expiration', models.DateField(help_text='')),
                ('primary_owner', models.CharField(max_length=100, verbose_name='Primary owner')),
                ('secondary_owner', models.CharField(max_length=100, verbose_name='Secondary owner')),
                ('registered_address', localflavor.us.models.USZipCodeField(help_text='', max_length=10)),
                ('description', models.CharField(max_length=100, verbose_name='Description')),
                ('record_owner', models.CharField(max_length=100, verbose_name='Record owner')),
                ('record_creation_date', models.DateField(help_text='')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicles', to='person.Person', verbose_name='Person')),
            ],
            options={
                'verbose_name': 'vehicle',
                'verbose_name_plural': 'vehicles',
            },
        ),
    ]
