# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-10-05 15:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vehicles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Case_equipment',
            fields=[
                ('case_equipment_id', models.AutoField(primary_key=True, serialize=False)),
                ('serial_number', models.CharField(max_length=100, verbose_name='Serial number')),
                ('email_address', models.EmailField(max_length=254, unique=True, verbose_name='Email address')),
                ('password', models.CharField(max_length=100, verbose_name='Password')),
                ('service_status', models.CharField(max_length=100, verbose_name='Service status')),
                ('date_purchased', models.DateField(help_text='')),
                ('price', models.FloatField(help_text='')),
                ('comments', models.CharField(max_length=100, verbose_name='Comments')),
                ('equipment_type', models.CharField(max_length=100, verbose_name='Equipment type')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='case_equipment', to='vehicles.Vehicle', verbose_name='Vehicle')),
            ],
            options={
                'verbose_name': 'case_equipment',
                'verbose_name_plural': 'case_equipments',
            },
        ),
    ]
