# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-10-06 20:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case_equipments', '0004_auto_20171006_1835'),
    ]

    operations = [
        migrations.RenameField(
            model_name='case_equipment',
            old_name='case_equipment_id',
            new_name='id',
        ),
        migrations.AlterField(
            model_name='case_equipment',
            name='date_purchased',
            field=models.DateField(help_text=''),
        ),
        migrations.AlterField(
            model_name='case_equipment',
            name='price',
            field=models.FloatField(help_text=''),
        ),
    ]
