# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-10-05 15:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('investigative_cases', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Update',
            fields=[
                ('update_id', models.AutoField(primary_key=True, serialize=False)),
                ('activity_date', models.DateField(help_text='')),
                ('activity_text', models.TextField(max_length=500, verbose_name='Activity text')),
                ('last_sent', models.CharField(max_length=100, verbose_name='Last sent')),
                ('vzaar_url', models.CharField(max_length=100, verbose_name='Vzzaar url')),
                ('investigative_case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='updates', to='investigative_cases.Investigative_case', verbose_name='Investigative case')),
            ],
            options={
                'verbose_name': 'update',
                'verbose_name_plural': 'updates',
            },
        ),
    ]
