# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-10-05 15:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Update_type',
            fields=[
                ('update_type_id', models.AutoField(primary_key=True, serialize=False)),
                ('update_type', models.CharField(max_length=100, verbose_name='Update type')),
            ],
            options={
                'verbose_name': 'update_type',
                'verbose_name_plural': 'update_types',
            },
        ),
    ]
