# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-10-05 15:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import localflavor.us.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('investigative_cases', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('assignment_id', models.AutoField(primary_key=True, serialize=False)),
                ('assignment_date', models.DateField(help_text='')),
                ('start_address', localflavor.us.models.USZipCodeField(help_text='', max_length=10)),
                ('investigator_id', models.IntegerField(verbose_name='Investigator ID')),
                ('record_owner', models.CharField(max_length=100, verbose_name='Record owner')),
                ('record_creation_date', models.DateField(help_text='')),
                ('investigative_case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignment', to='investigative_cases.Investigative_case', verbose_name='Investigative_case')),
            ],
            options={
                'verbose_name': 'assignment',
                'verbose_name_plural': 'assignments',
            },
        ),
    ]
