# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-10-05 15:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Case_video',
            fields=[
                ('case_video_id', models.AutoField(primary_key=True, serialize=False)),
                ('media_id', models.IntegerField(verbose_name='Media ID')),
                ('update_id', models.IntegerField(verbose_name='Update ID')),
                ('url', models.CharField(max_length=100, verbose_name='Url')),
                ('file_name', models.CharField(max_length=100, verbose_name='File name')),
                ('media_pin', models.IntegerField(verbose_name='Media pin')),
            ],
            options={
                'verbose_name': 'case_video',
                'verbose_name_plural': 'case_videos',
            },
        ),
    ]
